apiVersion: v1
kind: Service
metadata: 
  labels: 
    name: rolling-update
  name: rolling-update
spec: 
  ports:
    - port: 8080
      targetPort: 8080
      protocol : TCP
  selector: 
    name: rolling-update
  createExternalLoadBalancer : true
  type : NodePort 