apiVersion: v1
kind: Service
metadata: 
  labels: 
    name: rmq-svc
  name: rmq-svc
spec: 
  ports:
    - port: 5672
      targetPort: 5672
      protocol : TCP
      name : default
  selector: 
    type: rmq-node
  type : NodePort