apiVersion: v1
kind: Service
metadata: 
  labels: 
    name: rmq-node-1-ui-svc
  name: rmq-node-1-ui-svc
spec: 
  ports:
    - port: 15672
      targetPort: 15672
      protocol : TCP
      name : admin-port
  selector: 
    name: rmq-node-1
  type : NodePort