apiVersion: v1
kind: ReplicationController
metadata: 
  labels: 
    name: aspvnext-demo
  name: aspvnext-demo
spec: 
  replicas: 3
  selector: 
    name: aspvnext
  template: 
    metadata: 
      labels: 
        name: aspvnext
    spec: 
      containers: 
        - name: aspvnext
          image: mdevilliers/aspvnext-image:latest