apiVersion: v1
kind: Service
metadata: 
  labels: 
    name: aspvnext-service
  name: aspvnext-service
spec: 
  ports:
    - port: 5004
      targetPort: 5004
      protocol : TCP
  selector: 
    name: aspvnext
  type : LoadBalancer 