apiVersion: v1
kind: Service
metadata: 
  labels: 
    name: service-one
    external/public: "true"
  name: service-one
spec: 
  ports:
    - port: 80
      targetPort: 80
      protocol : TCP
  selector: 
    name: service-one-node
  createExternalLoadBalancer : true  
