apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        name: service-one-node
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80