apiVersion: v1
kind: Service
metadata: 
  labels: 
    name: service-two
    external/public: "true"
  name: service-two
spec: 
  ports:
    - port: 80
      targetPort: 80
      protocol : TCP
  selector: 
    name: service-two-node
  type : NodePort 
