apiVersion: v1
kind: Service
metadata: 
  labels: 
    name: service-one-node
    external/public : "true"
  annotations:
    external/name : service-one
    external/port : "8080"
    external/ytpe : http
    external/uri : /path1/child/
  name: service-one
spec: 
  ports:
    - port: 80
      targetPort: 80
      protocol : TCP
  selector: 
    name: service-one-node
  type : NodePort
