apiVersion: v1
kind: ReplicationController
metadata:
  name: teamcity
  namespace: default 
spec: 
  replicas: 1
  selector: 
    name: teamcity
  template: 
    metadata: 
      labels: 
        name: teamcity
    spec:
      containers:
      - image: smallimprovements/teamcity-docker
        imagePullPolicy: Always
        name: teamcity
        volumeMounts:
          - mountPath: /var/lib/teamcity
            name: teamcity-data
      volumes:
        - name: teamcity-data
          emptyDir: {}
