apiVersion: v1
kind: Service
metadata: 
  labels: 
    name: cluster-wide-service
    kubernetes.io/cluster-service: "true"
  name: monitoring-c-w-svc
spec: 
  ports:
    - port: 8080
      targetPort: 8080
  selector: 
    name: cluster-wide-service
    kubernetes.io/cluster-service: "true"
  type : NodePort 