apiVersion: v1
kind: Service
metadata: 
  labels: 
    name: sidecar-service
  name: sidecar-service
spec: 
  ports:
    - port: 8080
      targetPort: 8080
      protocol : TCP
  selector: 
    name: sidecar
  type : NodePort 