apiVersion: v1
kind: ReplicationController
metadata: 
  labels: 
    name: ambassador-demo
  name: ambassador-demo
spec: 
  replicas: 1
  selector: 
    name: ambassador
  template: 
    metadata: 
      labels: 
        name: ambassador
    spec: 
      containers: 
        - name: redis-proxy-ambassador
          image: mdevilliers/redis-proxy-ambassador-image:latest