apiVersion: v1
kind: Service
metadata: 
  labels: 
    name: ambassador-service
  name: ambassador-service
spec: 
  ports:
    - port: 6379
      targetPort: 6379
      protocol : TCP
  selector: 
    name: ambassador
  type : NodePort 