apiVersion: v1
kind: ReplicationController
metadata: 
  labels: 
    name: ambassador-demo-sharded-redis
  name: ambassador-demo-sharded-redis
spec: 
  replicas: 3
  selector: 
    name: redis-node
  template: 
    metadata: 
      labels: 
        name: redis-node
    spec: 
      containers: 
        - name: redis
          image: redis