apiVersion: v1
kind: Service
metadata: 
  labels: 
    name: secret-pod-service
  name: secret-pod-service
spec: 
  ports:
    - port: 8080
      targetPort: 8080
      protocol : TCP
  selector: 
    name: secrets-reader
  type : NodePort 