apiVersion: v1
kind: ReplicationController
metadata:
  name: secrets-reader
  namespace: default 
spec: 
  replicas: 3
  selector: 
    name: secrets-reader
  template: 
    metadata: 
      labels: 
        name: secrets-reader
    spec:
      containers:
      - image: mdevilliers/secrets-web-image:latest
        imagePullPolicy: Always
        name: secrets-reader
        volumeMounts:
        - mountPath: /etc/foo
          name: foo
          readOnly: true
      volumes:
      - name: foo
        secret:
          secretName: mysecret